# Generated by Django 5.0.1 on 2024-05-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon_hoc', models.CharField(max_length=20, unique=True)),
                ('ten_mon_hoc', models.CharField(max_length=100)),
                ('so_tin_chi', models.IntegerField()),
                ('ten_giang_vien', models.CharField(max_length=100)),
                ('so_luong_cmt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mssv', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('avatar', models.ImageField(default='avatars/avatar.jpg', upload_to='avatars/')),
                ('raw_password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_view_ratings', 'Can view ratings'), ('can_add_ratings', 'Can add ratings'), ('can_edit_ratings', 'Can edit ratings'), ('can_add_courses', 'Can add courses'), ('can_edit_courses', 'Can edit courses')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
                ('cau1', models.IntegerField()),
                ('cau2', models.IntegerField()),
                ('cau3', models.IntegerField()),
                ('cau4', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.course')),
            ],
            options={
                'unique_together': {('mssv', 'course')},
            },
        ),
    ]
